title: 'Biobags'
description: 'Biobags are made from sustainable, renewable plant materials such as sunflowers, corn, and potatoes. This makes them fully compostable and completely degradable in soil or water.'

url: 'biobags.co.nz'

twitter: 'TODO'

color-green-bg: '#bce1cc'
color-green-primary: '#137048'
color-green-primary-hover: '#2D8A62'
color-green-mid: '#67a88a'
color-green-accent: '#abd5bf'